name: CI
on: [push]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - run: pip3 install -r requirements.txt
            - run: pip3 install flake8
            - run: flake8 main.py
    doctest:
        runs-on: ubuntu-latest
        Strategy:
            matrix:
                python-version: [3.6, 3.7, 3.8, 3.9]
        steps:
            - run: python3 -m doctest main.py
                with: python-version: ${{matrix.python-version}}
        
            
